FROM ghcr.io/astral-sh/uv:bookworm-slim AS builder

ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy

ENV UV_PYTHON_INSTALL_DIR=/python

ENV UV_PYTHON_PREFERENCE=only-managed

ENV UV_PROJECT_ENVIRONMENT=/opt/venv

RUN uv python install 3.12

WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project --no-dev

COPY . /app

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --all-extras

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    {%- if db_type == "postgresql" %}
    libpq-dev \
    {%- elif db_type == "mysql" %}
    default-libmysqlclient-dev \
    build-essential \
    pkg-config \
    {%- endif %}
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder --chown=python:python /python /python

COPY --from=builder --chown=app:app /opt/venv /opt/venv

COPY --from=builder --chown=app:app /app /app

WORKDIR /app

ENV PATH="/opt/venv/bin:$PATH"

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
