include .env
export

DC = docker compose
MANAGE = uv run python manage.py
PRECOMMIT = uv run pre-commit

.PHONY: up
up:
	$(DC) up -d --build

.PHONY: down
down:
	$(DC) down

.PHONY: reset
reset: down up

.PHONY: clean-volumes
clean-volumes:
	$(DC) down -v --remove-orphans

.PHONY: rebuild
rebuild: clean-volumes
	$(DC) build --no-cache
	$(DC) up -d

.PHONY: logs
logs:
	$(DC) logs -f

.PHONY: migrate
migrate:
	$(DC) exec web $(MANAGE) migrate

.PHONY: migrations
migrations:
	$(DC) exec web $(MANAGE) makemigrations

.PHONY: admin
admin:
	$(DC) exec web $(MANAGE) create_admin

.PHONY: dj-shell
dj-shell:
	$(DC) exec web $(MANAGE) shell

.PHONY: db-shell
db-shell:
{%- if db_type == "postgresql" %}
	$(DC) exec postgresql psql -U $$POSTGRES_USER -d $$POSTGRES_DB
{%- elif db_type == "mysql" %}
	$(DC) exec mysql mysql -u $$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE
{%- endif %}

.PHONY: pre-commit-check
pre-commit-check:
	$(PRECOMMIT) run --all-files --show-diff-on-failure
